version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: lambda,dynamodb,apigateway,cognito
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  node:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    command: tail -f /dev/null
