service: todo-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
    AWS_REGION: us-east-1
    TODOS_TABLE: Todos
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
  stackName: todo-app-local

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: localstack
    edgePort: 4566

functions:
  createTodo:
    handler: lambda/createTodo.handler
    events:
      - http:
          path: todo
          method: post
          cors: true

  getTodos:
    handler: lambda/getTodos.handler
    events:
      - http:
          path: todos
          method: get
          cors: true

  updateTodo:
    handler: lambda/updateTodo.handler
    events:
      - http:
          path: todo/{id}
          method: put
          cors: true

  deleteTodo:
    handler: lambda/deleteTodo.handler
    events:
      - http:
          path: todo/{id}
          method: delete
          cors: true
